# NOTE: any changes in the requirements must also be reflected in
#   - setup.cfg
#   - requirements.txt
#   - install.rst
name: legwork
channels:
  - defaults
  - conda-forge
dependencies:
  - python >= 3.11
  - pip >= 24.0
  - numba >= 0.58
  - numpy >= 1.26
  - astropy >= 6.1
  - scipy >= 1.13
  - matplotlib >= 3.8
  - seaborn >= 0.13.2
  - schwimmbad >= 0.4.2
  - jupyter
  - ipython
  - pip:
    - legwork >= 0.5.0